// ═══════════════════════════════════════════════════════════════════════════
// Ícones Lucide referenciados pelo campo `icone` dos payloads clínicos.
// Apenas lucide-react: adicione aqui qualquer ícone novo usado nos payloads.
// ═══════════════════════════════════════════════════════════════════════════

import {
  type LucideIcon,
  Accessibility, Ambulance, Baby, Ban, Bath, Bed, Bone,
  BookOpen, Brain, Briefcase, Cake, Calculator, Calendar,
  CalendarClock, CalendarDays, ChartColumn, ChartLine, Check, CircleAlert,
  CircleDot, ClipboardCheck, Clock, EyeOff, Footprints, Frown, Gavel,
  GitBranch, GraduationCap, Heart, HeartPulse,
  History, Hospital, Hourglass, House, Info, Laptop, LifeBuoy, MapPin,
  Megaphone, MessageCircle, PenTool, Percent, PersonStanding, Pill,
  RefreshCw, Repeat, Scale, School, Shield, Stethoscope, TrendingDown,
  TriangleAlert, UserCheck, UserRound, Users, Zap,
} from "lucide-react";

const icones: Record<string, LucideIcon> = {
  Accessibility,
  Ambulance,
  Baby,
  Ban,
  Bath,
  Bed,
  Bone,
  BookOpen,
  Brain,
  Briefcase,
  Cake,
  Calculator,
  Calendar,
  CalendarClock,
  CalendarDays,
  ChartColumn,
  ChartLine,
  Check,
  CircleAlert,
  ClipboardCheck,
  Clock,
  EyeOff,
  Footprints,
  Frown,
  Gavel,
  GitBranch,
  GraduationCap,
  Heart,
  HeartPulse,
  History,
  Hospital,
  Hourglass,
  House,
  Info,
  Laptop,
  LifeBuoy,
  MapPin,
  Megaphone,
  MessageCircle,
  PenTool,
  Percent,
  PersonStanding,
  Pill,
  RefreshCw,
  Repeat,
  Scale,
  School,
  Shield,
  Stethoscope,
  TrendingDown,
  TriangleAlert,
  UserCheck,
  UserRound,
  Users,
  Zap,
};

export function getIcone(nome: string | null): LucideIcon {
  if (!nome) return CircleDot;
  return icones[nome] || CircleDot;
}
