// ═══════════════════════════════════════════════════════════════════════════
// Mapeamento Font Awesome → Lucide React
// ═══════════════════════════════════════════════════════════════════════════

import {
  type LucideIcon,
  User, UserPen, Cake, Users, GraduationCap, Briefcase,
  MessageSquarePlus, History, Baby, GitBranch, AlertTriangle,
  Ban, ClipboardList, UsersRound, EyeOff, Zap, TrendingUp,
  Layers, Pill, ClipboardCheck, FileText, Copy, Tag,
  ListChecks, BarChart3, Info, ChevronUp, RefreshCw, School,
  Laptop, Heart, Wallet, Home, Moon, ShieldAlert, HeartPulse,
  PersonStanding, MessageCircle, BookOpen, PenTool, Calculator,
  Hand, Footprints, Accessibility, Clock, Megaphone, Shield,
  MapPin, HandMetal, CircleDot, CheckCircle2, XCircle,
  Printer, RotateCcw, ChevronDown, Brain,
} from "lucide-react";

const mapaIcones: Record<string, LucideIcon> = {
  "fa-user": User,
  "fa-user-pen": UserPen,
  "fa-cake-candles": Cake,
  "fa-venus-mars": Users,
  "fa-graduation-cap": GraduationCap,
  "fa-briefcase": Briefcase,
  "fa-comment-medical": MessageSquarePlus,
  "fa-clock-rotate-left": History,
  "fa-child": Baby,
  "fa-arrows-split-up-and-left": GitBranch,
  "fa-triangle-exclamation": AlertTriangle,
  "fa-ban": Ban,
  "fa-notes-medical": ClipboardList,
  "fa-people-roof": UsersRound,
  "fa-eye-slash": EyeOff,
  "fa-bolt": Zap,
  "fa-chart-line": TrendingUp,
  "fa-layer-group": Layers,
  "fa-pills": Pill,
  "fa-clipboard-check": ClipboardCheck,
  "fa-brands fa-markdown": FileText,
  "fa-copy": Copy,
  "fa-tag": Tag,
  "fa-list-check": ListChecks,
  "fa-chart-bar": BarChart3,
  "fa-circle-info": Info,
  "fa-chevron-up": ChevronUp,
  "fa-chevron-down": ChevronDown,
  "fa-arrows-rotate": RefreshCw,
  "fa-school": School,
  "fa-laptop": Laptop,
  "fa-heart": Heart,
  "fa-wallet": Wallet,
  "fa-home": Home,
  "fa-moon": Moon,
  "fa-shield-halved": ShieldAlert,
  "fa-hand-holding-medical": HeartPulse,
  "fa-running": PersonStanding,
  "fa-comments": MessageCircle,
  "fa-book": BookOpen,
  "fa-book-open": BookOpen,
  "fa-pen-nib": PenTool,
  "fa-calculator": Calculator,
  "fa-hand-paper": Hand,
  "fa-shoe-prints": Footprints,
  "fa-wheelchair": Accessibility,
  "fa-clock": Clock,
  "fa-baby": Baby,
  "fa-baby-carriage": Baby,
  "fa-exclamation-triangle": AlertTriangle,
  "fa-heartbeat": HeartPulse,
  "fa-shield-alt": Shield,
  "fa-user-friends": Users,
  "fa-users": Users,
  "fa-sync-alt": RefreshCw,
  "fa-pen": PenTool,
  "fa-map-marker-alt": MapPin,
  "fa-hands": HandMetal,
  "fa-circle-check": CheckCircle2,
  "fa-circle-xmark": XCircle,
  "fa-message": MessageCircle,
  "fa-print": Printer,
  "fa-rotate-left": RotateCcw,
  "fa-bullhorn": Megaphone,
  "fa-brain": Brain,
};

export function getIcone(iconeFA: string | null): LucideIcon {
  if (!iconeFA) return CircleDot;
  return mapaIcones[iconeFA] || CircleDot;
}
