#!/usr/bin/env python3
"""Generate TypeScript/React DSM disorder modules from final clinical JSON.

The final clinical JSON files under ``dsm/output/final_json`` are the canonical
input for this step. This script intentionally does not rebuild, enrich, merge,
or regenerate clinical JSON from earlier pipeline layers. Its only responsibility
is:

    final_json -> TypeScript/React modules
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import shutil
import sys
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

STRUCTURAL_KEYS = {
    "meta",
    "estrutura_geral",
    "clusters_sintomas",
    "criterios_condicionais",
    "subtipos",
    "especificadores",
    "gravidade",
    "hierarquia",
    "dominios_impacto",
    "diagnostico_diferencial",
    "comorbidades_frequentes",
    "instrumentos_complementares",
    "prevalencia",
    "curso_desenvolvimento",
    "template_prontuario",
    "metadados_globais",
}

DISORDER_HINT_KEYS = STRUCTURAL_KEYS | {
    "id",
    "item_id",
    "name",
    "nome",
    "nome_completo",
    "chapter_id",
    "chapter_name",
}

COLLECTION_KEYS = (
    "items",
    "transtornos",
    "doencas",
    "disorders",
    "entries",
    "renderizaveis",
    "diagnoses",
)

REQUIRED_FIELDS = ("meta",)
SCHEMA_CRITICAL_FIELDS = ("meta.id", "meta.nome_completo")
GENERATED_HEADER = "// Auto-generated by scripts/generate_disorders.py. Do not edit manually.\n"


@dataclass
class SourceRecord:
    id: str
    payload: dict[str, Any]
    source: str


@dataclass
class Diagnostics:
    final_json_files_found: int = 0
    total_disorders_found: int = 0
    total_disorders_generated: int = 0
    expected_disorders_count: int | None = 58
    missing_required_fields: list[dict[str, str]] = field(default_factory=list)
    missing_meta: list[str] = field(default_factory=list)
    missing_id: list[str] = field(default_factory=list)
    missing_schema_critical_fields: list[dict[str, str]] = field(default_factory=list)
    schema_generation_errors: list[dict[str, str]] = field(default_factory=list)
    component_generation_errors: list[dict[str, str]] = field(default_factory=list)
    stale_generated_disorders: list[str] = field(default_factory=list)
    orphan_generated_files: list[str] = field(default_factory=list)
    duplicate_disorder_ids: list[dict[str, Any]] = field(default_factory=list)
    skipped_non_renderable_files: list[str] = field(default_factory=list)
    removed_files: list[str] = field(default_factory=list)
    dry_run_removals: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "final_json_files_found": self.final_json_files_found,
            "total_disorders_found": self.total_disorders_found,
            "total_disorders_generated": self.total_disorders_generated,
            "expected_disorders_count": self.expected_disorders_count,
            "missing_required_fields": self.missing_required_fields,
            "missing_meta": sorted(self.missing_meta),
            "missing_id": sorted(self.missing_id),
            "missing_schema_critical_fields": self.missing_schema_critical_fields,
            "schema_generation_errors": self.schema_generation_errors,
            "component_generation_errors": self.component_generation_errors,
            "stale_generated_disorders": sorted(self.stale_generated_disorders),
            "orphan_generated_files": sorted(self.orphan_generated_files),
            "duplicate_disorder_ids": self.duplicate_disorder_ids,
            "skipped_non_renderable_files": sorted(self.skipped_non_renderable_files),
            "removed_files": sorted(self.removed_files),
            "dry_run_removals": sorted(self.dry_run_removals),
            "warnings": self.warnings,
        }


def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_text(path: Path, content: str, dry_run: bool) -> None:
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def write_json(path: Path, payload: Any, dry_run: bool) -> None:
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def normalize_name(value: str | None) -> str:
    if not value:
        return ""
    normalized = unicodedata.normalize("NFKD", value)
    ascii_text = "".join(char for char in normalized if not unicodedata.combining(char))
    ascii_text = ascii_text.lower()
    ascii_text = re.sub(r"[^a-z0-9]+", "_", ascii_text)
    return re.sub(r"_+", "_", ascii_text).strip("_")


def pascal_case(identifier: str) -> str:
    parts = [part for part in normalize_name(identifier).split("_") if part]
    return "".join(part[:1].upper() + part[1:] for part in parts) or "Disorder"


def ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def ts_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def first_present(*values: Any) -> Any:
    for value in values:
        if value is not None and value != "":
            return value
    return None


def nested_get(payload: dict[str, Any], dotted_path: str) -> Any:
    current: Any = payload
    for key in dotted_path.split("."):
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current


def get_meta(payload: dict[str, Any]) -> dict[str, Any]:
    meta = payload.get("meta")
    return meta if isinstance(meta, dict) else {}


def disorder_id(payload: dict[str, Any], source_stem: str | None = None) -> str | None:
    meta = get_meta(payload)
    raw = first_present(meta.get("id"), payload.get("id"), payload.get("item_id"), payload.get("slug"))
    if isinstance(raw, str) and raw.strip():
        return normalize_name(raw)
    if source_stem:
        return normalize_name(source_stem)
    return None


def disorder_name(payload: dict[str, Any]) -> str | None:
    meta = get_meta(payload)
    raw = first_present(
        meta.get("nome_completo"),
        meta.get("nome"),
        payload.get("nome_completo"),
        payload.get("nome"),
        payload.get("name"),
        payload.get("title"),
    )
    return str(raw) if raw is not None else None


def is_probable_disorder(payload: Any) -> bool:
    if not isinstance(payload, dict):
        return False
    meta = payload.get("meta")
    if isinstance(meta, dict) and (meta.get("id") or meta.get("nome_completo") or meta.get("nome")):
        return True
    key_hits = sum(1 for key in DISORDER_HINT_KEYS if key in payload)
    structural_hits = sum(1 for key in STRUCTURAL_KEYS if key in payload)
    return key_hits >= 3 or structural_hits >= 2


def iter_disorder_payloads(document: Any) -> Iterable[dict[str, Any]]:
    if is_probable_disorder(document):
        yield document
        return
    if isinstance(document, dict):
        for key in COLLECTION_KEYS:
            value = document.get(key)
            if isinstance(value, list):
                for item in value:
                    if is_probable_disorder(item):
                        yield item
            elif isinstance(value, dict):
                for item_key, item in value.items():
                    if is_probable_disorder(item):
                        item_copy = copy.deepcopy(item)
                        item_copy.setdefault("id", item_key)
                        yield item_copy
    elif isinstance(document, list):
        for item in document:
            if is_probable_disorder(item):
                yield item


def validate_final_payload(did: str | None, payload: dict[str, Any], source: Path, diagnostics: Diagnostics) -> None:
    for field_name in REQUIRED_FIELDS:
        if payload.get(field_name) in (None, ""):
            diagnostics.missing_required_fields.append({"id": did or "<missing-id>", "field": field_name, "source": str(source)})
    if not isinstance(payload.get("meta"), dict):
        diagnostics.missing_meta.append(str(source))
    if not did:
        diagnostics.missing_id.append(str(source))
    for field_name in SCHEMA_CRITICAL_FIELDS:
        if nested_get(payload, field_name) in (None, ""):
            diagnostics.missing_schema_critical_fields.append({"id": did or "<missing-id>", "field": field_name, "source": str(source)})


def load_final_records(final_json_dir: Path, diagnostics: Diagnostics) -> dict[str, SourceRecord]:
    records: dict[str, SourceRecord] = {}
    if not final_json_dir.exists():
        diagnostics.warnings.append(f"Final JSON directory not found: {final_json_dir}")
        return records

    json_paths = sorted(path for path in final_json_dir.glob("*.json") if path.is_file())
    diagnostics.final_json_files_found = len(json_paths)

    for path in json_paths:
        document = read_json(path)
        payloads = list(iter_disorder_payloads(document))
        if not payloads:
            diagnostics.skipped_non_renderable_files.append(str(path))
            continue
        for payload in payloads:
            did = disorder_id(payload)
            validate_final_payload(did, payload, path, diagnostics)
            if not did:
                continue
            if did in records:
                diagnostics.duplicate_disorder_ids.append({"id": did, "sources": [records[did].source, str(path)]})
                continue
            records[did] = SourceRecord(did, copy.deepcopy(payload), str(path))

    diagnostics.total_disorders_found = len(records)
    return records


def make_config(data: dict[str, Any], did: str) -> dict[str, Any]:
    meta = get_meta(data)
    codigo = meta.get("codigo") if isinstance(meta.get("codigo"), dict) else {}
    nome = str(first_present(meta.get("nome_completo"), meta.get("nome"), data.get("nome_completo"), data.get("nome"), did))
    tags: list[str] = []
    for value in (meta.get("grupo"), data.get("estrutura_geral"), meta.get("faixa_etaria_alvo")):
        if isinstance(value, str) and value:
            tags.append(value)
    return {
        "id": did,
        "nome": nome,
        "sigla": meta.get("sigla") or data.get("sigla"),
        "capitulo_id": meta.get("capitulo_id") or data.get("capitulo_id") or data.get("chapter_id"),
        "capitulo_nome": meta.get("capitulo") or data.get("capitulo_nome") or data.get("chapter_name"),
        "codigo_dsm5": codigo.get("dsm5") or data.get("codigo_dsm5") or data.get("dsm5"),
        "codigo_cid10": codigo.get("cid10") or data.get("codigo_cid10") or data.get("cid10"),
        "codigo_cid11": codigo.get("cid11") or data.get("codigo_cid11"),
        "faixa_etaria_alvo": meta.get("faixa_etaria_alvo") or data.get("faixa_etaria_alvo"),
        "estrutura_geral": data.get("estrutura_geral") or data.get("estrutura_diagnostica"),
        "render_component": "GenericDisorderRenderer",
        "route_path": f"/app/assess/{did}",
        "tags": sorted(set(tags)),
    }


def render_schema_ts(disorder_id_value: str) -> str:
    schema_name = f"{pascal_case(disorder_id_value)}Schema"
    type_name = pascal_case(disorder_id_value)
    return f"""{GENERATED_HEADER}import {{ z }} from \"zod\";
import {{ ClinicalDisorderSchema }} from \"../_shared/schema\";

export const {schema_name} = ClinicalDisorderSchema.extend({{
  meta: ClinicalDisorderSchema.shape.meta.extend({{
    id: z.literal({ts_string(disorder_id_value)}),
  }}),
}}).passthrough();

export type {type_name} = z.infer<typeof {schema_name}>;
export const DisorderSchema = {schema_name};
export type Disorder = {type_name};
"""


def render_data_ts(disorder_id_value: str, data: dict[str, Any]) -> str:
    schema_name = f"{pascal_case(disorder_id_value)}Schema"
    return f"""{GENERATED_HEADER}import {{ {schema_name} }} from \"./schema\";

export const data = {schema_name}.parse({ts_json(data)});
export type DisorderData = typeof data;
"""


def render_config_ts(config: dict[str, Any]) -> str:
    return f"""{GENERATED_HEADER}import type {{ DisorderRenderConfig }} from \"../_shared/DisorderRenderer\";

export const config = {ts_json(config)} as const satisfies DisorderRenderConfig;
export type DisorderConfig = typeof config;
"""


def render_index_tsx(disorder_id_value: str, config: dict[str, Any]) -> str:
    component_name = pascal_case(disorder_id_value)
    return f"""{GENERATED_HEADER}import {{ DisorderRenderer }} from \"../_shared/DisorderRenderer\";
import {{ config }} from \"./config\";
import {{ data }} from \"./data\";

export function {component_name}() {{
  return <DisorderRenderer data={{data}} config={{config}} />;
}}

export {{ config, data }};
export default {component_name};
export const meta = {{
  id: config.id,
  nome: config.nome,
  sigla: {ts_json(config.get('sigla'))},
  capituloId: config.capitulo_id,
}};
"""


def render_registry_ts(configs: list[dict[str, Any]]) -> str:
    entries = "\n".join(f"  {cfg['id']}: () => import(\"./{cfg['id']}\")," for cfg in configs)
    meta = [{"id": cfg["id"], "nome": cfg["nome"], "capitulo_id": cfg.get("capitulo_id"), "route_path": cfg["route_path"]} for cfg in configs]
    return f"""{GENERATED_HEADER}import type {{ ComponentType }} from \"react\";

export interface GeneratedDisorderModule {{
  default: ComponentType;
}}

export const generatedDisorderImports: Record<string, () => Promise<GeneratedDisorderModule>> = {{
{entries}
}};

export const generatedDisorderMetadata = {ts_json(meta)} as const;
export type GeneratedDisorderId = keyof typeof generatedDisorderImports;
"""


def render_index_aggregator(configs: list[dict[str, Any]]) -> str:
    exports = "\n".join(f"export * as {pascal_case(cfg['id'])} from \"./{cfg['id']}\";" for cfg in configs)
    return f"{GENERATED_HEADER}export * from \"./registry\";\nexport * from \"./schemas\";\n{exports}\n"


def render_schemas_aggregator(configs: list[dict[str, Any]]) -> str:
    exports = "\n".join(f"export {{ {pascal_case(cfg['id'])}Schema }} from \"./{cfg['id']}/schema\";" for cfg in configs)
    return f"{GENERATED_HEADER}export {{ ClinicalDisorderSchema }} from \"./_shared/schema\";\n{exports}\n"


def find_generated_orphans(out_dir: Path, canonical_ids: set[str]) -> list[str]:
    if not out_dir.exists():
        return []
    orphans = []
    for child in out_dir.iterdir():
        if child.is_dir() and not child.name.startswith("_") and child.name not in canonical_ids:
            marker_files = [child / name for name in ("config.ts", "data.ts", "schema.ts", "index.tsx")]
            if any(path.exists() for path in marker_files):
                orphans.append(str(child))
    return orphans


def clean_orphans(paths: list[str], out_dir: Path, dry_run: bool, diagnostics: Diagnostics) -> None:
    out_root = out_dir.resolve()
    for raw_path in paths:
        path = Path(raw_path).resolve()
        try:
            path.relative_to(out_root)
        except ValueError:
            diagnostics.warnings.append(f"Refusing to remove path outside out-dir: {path}")
            continue
        if dry_run:
            diagnostics.dry_run_removals.append(str(path))
        else:
            shutil.rmtree(path)
            diagnostics.removed_files.append(str(path))


def generate(args: argparse.Namespace) -> Diagnostics:
    diagnostics = Diagnostics(expected_disorders_count=args.expected_count)
    final_records = load_final_records(args.final_json_dir, diagnostics)
    canonical_ids = set(final_records)
    diagnostics.orphan_generated_files = find_generated_orphans(args.out_dir, canonical_ids)
    diagnostics.stale_generated_disorders = diagnostics.orphan_generated_files[:]

    if args.clean_stale_generated or args.dry_run:
        clean_orphans(diagnostics.orphan_generated_files, args.out_dir, args.dry_run, diagnostics)

    configs: list[dict[str, Any]] = []
    for did in sorted(final_records):
        record = final_records[did]
        config = make_config(record.payload, did)
        configs.append(config)
        disorder_dir = args.out_dir / did
        try:
            write_text(disorder_dir / "schema.ts", render_schema_ts(did), args.dry_run)
        except Exception as exc:  # noqa: BLE001 - diagnostic tool must continue across disorders
            diagnostics.schema_generation_errors.append({"id": did, "error": str(exc), "source": record.source})
        try:
            write_text(disorder_dir / "data.ts", render_data_ts(did, record.payload), args.dry_run)
            write_text(disorder_dir / "config.ts", render_config_ts(config), args.dry_run)
            write_text(disorder_dir / "index.tsx", render_index_tsx(did, config), args.dry_run)
        except Exception as exc:  # noqa: BLE001 - diagnostic tool must continue across disorders
            diagnostics.component_generation_errors.append({"id": did, "error": str(exc), "source": record.source})

    diagnostics.total_disorders_generated = len(configs)
    if diagnostics.expected_disorders_count is not None and len(configs) != diagnostics.expected_disorders_count:
        diagnostics.warnings.append(
            f"Generated {len(configs)} disorders from final JSON, expected {diagnostics.expected_disorders_count}. "
            "Check --final-json-dir or pass --expected-count with the canonical value."
        )

    write_text(args.out_dir / "registry.ts", render_registry_ts(configs), args.dry_run)
    write_text(args.out_dir / "index.ts", render_index_aggregator(configs), args.dry_run)
    write_text(args.out_dir / "schemas.ts", render_schemas_aggregator(configs), args.dry_run)
    # Even in --dry-run mode the diagnostic report is intentionally written;
    # dry-run only suppresses generated modules and destructive cleanup.
    write_json(args.diagnostics, diagnostics.to_dict(), False)
    return diagnostics


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate DSM disorder TypeScript/React modules from final clinical JSON.")
    parser.add_argument("--final-json-dir", type=Path, default=Path("dsm/output/final_json"), help="Directory with final, already-consolidated clinical JSON files.")
    parser.add_argument("--out-dir", type=Path, default=Path("src/generated/disorders"), help="Output directory for generated modules.")
    parser.add_argument("--diagnostics", type=Path, default=Path("generation_diagnostics.json"), help="Diagnostics report path.")
    parser.add_argument("--expected-count", type=int, default=58, help="Expected canonical renderable disorder count. Use 0 to disable.")
    parser.add_argument("--dry-run", action="store_true", help="Analyze and report without writing generated files or deleting stale output.")
    parser.add_argument("--clean-stale-generated", action="store_true", help="Remove stale generated disorder directories under --out-dir only.")
    args = parser.parse_args(argv)
    if args.expected_count == 0:
        args.expected_count = None
    return args


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    diagnostics = generate(args)
    print(json.dumps(diagnostics.to_dict(), ensure_ascii=False, indent=2))
    return 1 if diagnostics.schema_generation_errors or diagnostics.component_generation_errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
