#!/usr/bin/env python3
"""Generate TypeScript/React DSM disorder modules from rich clinical JSON.

The generator treats rich chapter JSON as the canonical structural source and
merges auxiliary datasets by stable disorder id. Name-based matching exists only
as an audited fallback for legacy inputs that lack ids.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import shutil
import sys
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

STRUCTURAL_KEYS = {
    "meta",
    "estrutura_geral",
    "clusters_sintomas",
    "criterios_condicionais",
    "subtipos",
    "especificadores",
    "gravidade",
    "hierarquia",
    "dominios_impacto",
    "diagnostico_diferencial",
    "comorbidades_frequentes",
    "instrumentos_complementares",
    "prevalencia",
    "curso_desenvolvimento",
    "template_prontuario",
    "metadados_globais",
}

DISORDER_HINT_KEYS = STRUCTURAL_KEYS | {
    "id",
    "item_id",
    "name",
    "nome",
    "nome_completo",
    "chapter_id",
    "chapter_name",
}

COLLECTION_KEYS = (
    "transtornos",
    "doencas",
    "disorders",
    "items",
    "entries",
    "renderizaveis",
    "diagnoses",
)

GENERATED_HEADER = "// Auto-generated by scripts/generate_disorders.py. Do not edit manually.\n"


@dataclass
class SourceRecord:
    id: str
    payload: dict[str, Any]
    source: str
    chapter_id: str | None = None
    chapter_name: str | None = None
    matched_by: str = "id"


@dataclass
class Diagnostics:
    total_chapters_found: int = 0
    total_disorders_found: int = 0
    total_disorders_generated: int = 0
    expected_disorders_count: int | None = 58
    missing_super_enrichment: list[str] = field(default_factory=list)
    missing_cid11: list[str] = field(default_factory=list)
    missing_master_metadata: list[str] = field(default_factory=list)
    missing_inventory: list[str] = field(default_factory=list)
    missing_hierarchy: list[str] = field(default_factory=list)
    orphan_super_files: list[str] = field(default_factory=list)
    orphan_generated_files: list[str] = field(default_factory=list)
    stale_app_disorders: list[str] = field(default_factory=list)
    ambiguous_matches: list[dict[str, Any]] = field(default_factory=list)
    schema_generation_errors: list[dict[str, str]] = field(default_factory=list)
    component_generation_errors: list[dict[str, str]] = field(default_factory=list)
    merge_conflicts: list[dict[str, str]] = field(default_factory=list)
    removed_files: list[str] = field(default_factory=list)
    dry_run_removals: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "total_chapters_found": self.total_chapters_found,
            "total_disorders_found": self.total_disorders_found,
            "total_disorders_generated": self.total_disorders_generated,
            "expected_disorders_count": self.expected_disorders_count,
            "missing_super_enrichment": sorted(self.missing_super_enrichment),
            "missing_cid11": sorted(self.missing_cid11),
            "missing_master_metadata": sorted(self.missing_master_metadata),
            "missing_inventory": sorted(self.missing_inventory),
            "missing_hierarchy": sorted(self.missing_hierarchy),
            "orphan_super_files": sorted(self.orphan_super_files),
            "orphan_generated_files": sorted(self.orphan_generated_files),
            "stale_app_disorders": sorted(self.stale_app_disorders),
            "ambiguous_matches": self.ambiguous_matches,
            "schema_generation_errors": self.schema_generation_errors,
            "component_generation_errors": self.component_generation_errors,
            "merge_conflicts": self.merge_conflicts,
            "removed_files": sorted(self.removed_files),
            "dry_run_removals": sorted(self.dry_run_removals),
            "warnings": self.warnings,
        }


def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_text(path: Path, content: str, dry_run: bool) -> None:
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def write_json(path: Path, payload: Any, dry_run: bool) -> None:
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def normalize_name(value: str | None) -> str:
    if not value:
        return ""
    normalized = unicodedata.normalize("NFKD", value)
    ascii_text = "".join(char for char in normalized if not unicodedata.combining(char))
    ascii_text = ascii_text.lower()
    ascii_text = re.sub(r"[^a-z0-9]+", "_", ascii_text)
    return re.sub(r"_+", "_", ascii_text).strip("_")


def pascal_case(identifier: str) -> str:
    parts = [part for part in normalize_name(identifier).split("_") if part]
    return "".join(part[:1].upper() + part[1:] for part in parts) or "Disorder"


def ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def ts_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def first_present(*values: Any) -> Any:
    for value in values:
        if value is not None and value != "":
            return value
    return None


def get_meta(payload: dict[str, Any]) -> dict[str, Any]:
    meta = payload.get("meta")
    return meta if isinstance(meta, dict) else {}


def disorder_id(payload: dict[str, Any], source_stem: str | None = None) -> str | None:
    meta = get_meta(payload)
    raw = first_present(meta.get("id"), payload.get("id"), payload.get("item_id"), payload.get("slug"))
    if isinstance(raw, str) and raw.strip():
        return normalize_name(raw)
    if source_stem:
        return normalize_name(source_stem)
    return None


def disorder_name(payload: dict[str, Any]) -> str | None:
    meta = get_meta(payload)
    raw = first_present(
        meta.get("nome_completo"),
        meta.get("nome"),
        payload.get("nome_completo"),
        payload.get("nome"),
        payload.get("name"),
        payload.get("title"),
    )
    return str(raw) if raw is not None else None


def is_probable_disorder(payload: Any) -> bool:
    if not isinstance(payload, dict):
        return False
    meta = payload.get("meta")
    if isinstance(meta, dict) and (meta.get("id") or meta.get("nome_completo") or meta.get("nome")):
        return True
    key_hits = sum(1 for key in DISORDER_HINT_KEYS if key in payload)
    structural_hits = sum(1 for key in STRUCTURAL_KEYS if key in payload)
    return key_hits >= 3 or structural_hits >= 2


def chapter_metadata(document: Any, path: Path) -> tuple[str | None, str | None]:
    if not isinstance(document, dict):
        return None, None
    candidates: list[dict[str, Any]] = []
    for key in ("chapter", "capitulo", "meta", "metadata", "metadados"):
        value = document.get(key)
        if isinstance(value, dict):
            candidates.append(value)
    candidates.append(document)
    for candidate in candidates:
        chapter_id = first_present(candidate.get("capitulo_id"), candidate.get("chapter_id"), candidate.get("id"))
        chapter_name = first_present(candidate.get("capitulo_nome"), candidate.get("chapter_name"), candidate.get("nome"), candidate.get("name"))
        if chapter_id or chapter_name:
            return str(chapter_id) if chapter_id is not None else None, str(chapter_name) if chapter_name is not None else None
    match = re.match(r"^(\d{1,2})", path.stem)
    return (match.group(1).zfill(2) if match else None), None


def iter_disorder_payloads(document: Any, path: Path) -> Iterable[dict[str, Any]]:
    if is_probable_disorder(document):
        yield document
        return
    if isinstance(document, dict):
        for key in COLLECTION_KEYS:
            value = document.get(key)
            if isinstance(value, list):
                for item in value:
                    if is_probable_disorder(item):
                        yield item
            elif isinstance(value, dict):
                for item_key, item in value.items():
                    if is_probable_disorder(item):
                        item_copy = copy.deepcopy(item)
                        item_copy.setdefault("id", item_key)
                        yield item_copy
        for value in document.values():
            if isinstance(value, dict) and is_probable_disorder(value):
                yield value
    elif isinstance(document, list):
        for item in document:
            if is_probable_disorder(item):
                yield item


def load_rich_records(rich_dir: Path, diagnostics: Diagnostics) -> dict[str, SourceRecord]:
    records: dict[str, SourceRecord] = {}
    if not rich_dir.exists():
        diagnostics.warnings.append(f"Rich directory not found: {rich_dir}")
        return records
    json_paths = sorted(path for path in rich_dir.rglob("*.json") if path.is_file())
    diagnostics.total_chapters_found = len(json_paths)
    for path in json_paths:
        document = read_json(path)
        chapter_id, chapter_name = chapter_metadata(document, path)
        for payload in iter_disorder_payloads(document, path):
            did = disorder_id(payload, path.stem if is_probable_disorder(document) else None)
            if not did:
                diagnostics.warnings.append(f"Skipped disorder without id in {path}")
                continue
            cloned = copy.deepcopy(payload)
            meta = cloned.setdefault("meta", {})
            if isinstance(meta, dict):
                meta.setdefault("id", did)
                if chapter_id:
                    meta.setdefault("capitulo_id", chapter_id)
                if chapter_name:
                    meta.setdefault("capitulo", chapter_name)
            if did in records:
                diagnostics.ambiguous_matches.append({"id": did, "sources": [records[did].source, str(path)]})
                continue
            records[did] = SourceRecord(did, cloned, str(path), chapter_id, chapter_name)
    diagnostics.total_disorders_found = len(records)
    return records


def index_payloads_by_id(path_or_dir: Path, diagnostics: Diagnostics, label: str) -> tuple[dict[str, Any], dict[str, list[tuple[str, Any]]]]:
    by_id: dict[str, Any] = {}
    by_name: dict[str, list[tuple[str, Any]]] = {}
    paths: list[Path]
    if not path_or_dir.exists():
        diagnostics.warnings.append(f"{label} not found: {path_or_dir}")
        return by_id, by_name
    if path_or_dir.is_dir():
        paths = sorted(item for item in path_or_dir.rglob("*.json") if item.is_file())
    else:
        paths = [path_or_dir]
    for path in paths:
        document = read_json(path)
        payloads = list(iter_disorder_payloads(document, path))
        if not payloads and isinstance(document, dict):
            payloads = [document]
        for payload in payloads:
            if not isinstance(payload, dict):
                continue
            did = disorder_id(payload, path.stem)
            if did:
                by_id.setdefault(did, copy.deepcopy(payload))
            name_key = normalize_name(disorder_name(payload))
            if name_key:
                by_name.setdefault(name_key, []).append((str(path), copy.deepcopy(payload)))
    return by_id, by_name


def lookup_aux(
    disorder: SourceRecord,
    by_id: dict[str, Any],
    by_name: dict[str, list[tuple[str, Any]]],
    label: str,
    diagnostics: Diagnostics,
) -> Any | None:
    if disorder.id in by_id:
        return by_id[disorder.id]
    name_key = normalize_name(disorder_name(disorder.payload))
    matches = by_name.get(name_key, []) if name_key else []
    if len(matches) == 1:
        diagnostics.ambiguous_matches.append({"id": disorder.id, "label": label, "matched_by": "normalized_name", "source": matches[0][0]})
        return matches[0][1]
    if len(matches) > 1:
        diagnostics.ambiguous_matches.append({"id": disorder.id, "label": label, "matched_by": "normalized_name", "sources": [source for source, _ in matches]})
    return None


def scalar_code_from(value: Any) -> str | None:
    if isinstance(value, str) and value.strip():
        return value.strip()
    if isinstance(value, dict):
        for key in ("cid11", "cid_11", "codigo_cid11", "code", "codigo"):
            result = scalar_code_from(value.get(key))
            if result:
                return result
    return None


def merge_disorder(
    base: SourceRecord,
    super_payload: Any | None,
    cid11_payload: Any | None,
    master_payload: Any | None,
    inventory_payload: Any | None,
    hierarchy_payload: Any | None,
    diagnostics: Diagnostics,
) -> dict[str, Any]:
    merged = copy.deepcopy(base.payload)
    meta = merged.setdefault("meta", {})
    if not isinstance(meta, dict):
        meta = {"id": base.id}
        merged["meta"] = meta
    meta["id"] = base.id
    meta.setdefault("capitulo_id", base.chapter_id)
    meta.setdefault("capitulo", base.chapter_name)

    codigo = meta.setdefault("codigo", {})
    if not isinstance(codigo, dict):
        codigo = {}
        meta["codigo"] = codigo
    cid11_code = scalar_code_from(cid11_payload)
    if cid11_code:
        codigo["cid11"] = cid11_code
        merged["codigo_cid11"] = cid11_code
    else:
        codigo.setdefault("cid11", None)
        diagnostics.missing_cid11.append(base.id)

    if super_payload is None:
        diagnostics.missing_super_enrichment.append(base.id)
    elif isinstance(super_payload, dict):
        conflicts = sorted(key for key in STRUCTURAL_KEYS if key in super_payload and key in merged and super_payload[key] != merged[key])
        for key in conflicts:
            diagnostics.merge_conflicts.append({"id": base.id, "field": key, "policy": "rich_preserved_super_namespaced"})
        merged["super_enrichment"] = copy.deepcopy(super_payload)

    if master_payload is None:
        diagnostics.missing_master_metadata.append(base.id)
    else:
        merged["master_metadata"] = copy.deepcopy(master_payload)

    if inventory_payload is None:
        diagnostics.missing_inventory.append(base.id)
    else:
        merged["inventory_notes"] = copy.deepcopy(inventory_payload)

    if hierarchy_payload is None:
        diagnostics.missing_hierarchy.append(base.id)
    else:
        merged["hierarchy_index"] = copy.deepcopy(hierarchy_payload)
        if "hierarquia" not in merged:
            merged["hierarquia"] = copy.deepcopy(hierarchy_payload)

    merged["$schema_version"] = str(merged.get("$schema_version") or "2.0.0")
    return merged


def make_config(data: dict[str, Any]) -> dict[str, Any]:
    meta = get_meta(data)
    codigo = meta.get("codigo") if isinstance(meta.get("codigo"), dict) else {}
    did = str(meta.get("id"))
    nome = str(first_present(meta.get("nome_completo"), meta.get("nome"), data.get("nome_completo"), data.get("nome"), did))
    tags: list[str] = []
    for value in (meta.get("grupo"), data.get("estrutura_geral"), meta.get("faixa_etaria_alvo")):
        if isinstance(value, str) and value:
            tags.append(value)
    return {
        "id": did,
        "nome": nome,
        "sigla": meta.get("sigla"),
        "capitulo_id": meta.get("capitulo_id") or data.get("chapter_id"),
        "capitulo_nome": meta.get("capitulo") or data.get("chapter_name"),
        "codigo_dsm5": codigo.get("dsm5") or data.get("dsm5"),
        "codigo_cid10": codigo.get("cid10") or data.get("cid10"),
        "codigo_cid11": codigo.get("cid11") or data.get("codigo_cid11"),
        "faixa_etaria_alvo": meta.get("faixa_etaria_alvo"),
        "estrutura_geral": data.get("estrutura_geral") or data.get("estrutura_diagnostica"),
        "render_component": "GenericDisorderRenderer",
        "route_path": f"/app/assess/{did}",
        "tags": sorted(set(tags)),
    }


def render_schema_ts(disorder_id_value: str) -> str:
    schema_name = f"{pascal_case(disorder_id_value)}Schema"
    type_name = pascal_case(disorder_id_value)
    return f"""{GENERATED_HEADER}import {{ z }} from \"zod\";
import {{ ClinicalDisorderSchema }} from \"../_shared/schema\";

export const {schema_name} = ClinicalDisorderSchema.extend({{
  meta: ClinicalDisorderSchema.shape.meta.extend({{
    id: z.literal({ts_string(disorder_id_value)}),
  }}),
}}).passthrough();

export type {type_name} = z.infer<typeof {schema_name}>;
export const DisorderSchema = {schema_name};
export type Disorder = {type_name};
"""


def render_data_ts(disorder_id_value: str, data: dict[str, Any]) -> str:
    schema_name = f"{pascal_case(disorder_id_value)}Schema"
    return f"""{GENERATED_HEADER}import {{ {schema_name} }} from \"./schema\";

export const data = {schema_name}.parse({ts_json(data)});
export type DisorderData = typeof data;
"""


def render_config_ts(config: dict[str, Any]) -> str:
    return f"""{GENERATED_HEADER}import type {{ DisorderRenderConfig }} from \"../_shared/DisorderRenderer\";

export const config = {ts_json(config)} as const satisfies DisorderRenderConfig;
export type DisorderConfig = typeof config;
"""


def render_index_tsx(disorder_id_value: str, config: dict[str, Any]) -> str:
    component_name = pascal_case(disorder_id_value)
    return f"""{GENERATED_HEADER}import {{ DisorderRenderer }} from \"../_shared/DisorderRenderer\";
import {{ config }} from \"./config\";
import {{ data }} from \"./data\";

export function {component_name}() {{
  return <DisorderRenderer data={{data}} config={{config}} />;
}}

export {{ config, data }};
export default {component_name};
export const meta = {{
  id: config.id,
  nome: config.nome,
  sigla: {ts_json(config.get('sigla'))},
  capituloId: config.capitulo_id,
}};
"""


def render_registry_ts(configs: list[dict[str, Any]]) -> str:
    entries = "\n".join(f"  {cfg['id']}: () => import(\"./{cfg['id']}\")," for cfg in configs)
    meta = [{"id": cfg["id"], "nome": cfg["nome"], "capitulo_id": cfg.get("capitulo_id"), "route_path": cfg["route_path"]} for cfg in configs]
    return f"""{GENERATED_HEADER}import type {{ ComponentType }} from \"react\";

export interface GeneratedDisorderModule {{
  default: ComponentType;
}}

export const generatedDisorderImports: Record<string, () => Promise<GeneratedDisorderModule>> = {{
{entries}
}};

export const generatedDisorderMetadata = {ts_json(meta)} as const;
export type GeneratedDisorderId = keyof typeof generatedDisorderImports;
"""


def render_index_aggregator(configs: list[dict[str, Any]]) -> str:
    exports = "\n".join(f"export * as {pascal_case(cfg['id'])} from \"./{cfg['id']}\";" for cfg in configs)
    return f"{GENERATED_HEADER}export * from \"./registry\";\nexport * from \"./schemas\";\n{exports}\n"


def render_schemas_aggregator(configs: list[dict[str, Any]]) -> str:
    exports = "\n".join(f"export {{ {pascal_case(cfg['id'])}Schema }} from \"./{cfg['id']}/schema\";" for cfg in configs)
    return f"{GENERATED_HEADER}export {{ ClinicalDisorderSchema }} from \"./_shared/schema\";\n{exports}\n"


def find_generated_orphans(out_dir: Path, canonical_ids: set[str]) -> list[str]:
    if not out_dir.exists():
        return []
    orphans = []
    for child in out_dir.iterdir():
        if child.is_dir() and not child.name.startswith("_") and child.name not in canonical_ids:
            marker_files = [child / name for name in ("config.ts", "data.ts", "schema.ts", "index.tsx")]
            if any(path.exists() for path in marker_files):
                orphans.append(str(child))
    return orphans


def clean_orphans(paths: list[str], out_dir: Path, dry_run: bool, diagnostics: Diagnostics) -> None:
    out_root = out_dir.resolve()
    for raw_path in paths:
        path = Path(raw_path).resolve()
        try:
            path.relative_to(out_root)
        except ValueError:
            diagnostics.warnings.append(f"Refusing to remove path outside out-dir: {path}")
            continue
        if dry_run:
            diagnostics.dry_run_removals.append(str(path))
        else:
            shutil.rmtree(path)
            diagnostics.removed_files.append(str(path))



def copy_shared_templates(out_dir: Path, dry_run: bool, diagnostics: Diagnostics) -> None:
    """Copy reusable TypeScript renderer/schema templates into the generated tree."""
    template_root = Path(__file__).resolve().parents[1] / "src" / "generated" / "disorders" / "_shared"
    if not template_root.exists():
        diagnostics.warnings.append(f"Shared template directory not found: {template_root}")
        return
    for source in sorted(template_root.glob("*.ts*")):
        target = out_dir / "_shared" / source.name
        if source.resolve() == target.resolve():
            continue
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")

def generate(args: argparse.Namespace) -> Diagnostics:
    diagnostics = Diagnostics(expected_disorders_count=args.expected_count)
    copy_shared_templates(args.out_dir, args.dry_run, diagnostics)
    rich_records = load_rich_records(args.rich_dir, diagnostics)
    super_by_id, super_by_name = index_payloads_by_id(args.super_dir, diagnostics, "super-dir")
    cid11_by_id, cid11_by_name = index_payloads_by_id(args.cid11, diagnostics, "cid11")
    master_by_id, master_by_name = index_payloads_by_id(args.master_index, diagnostics, "master-index")
    inventory_by_id, inventory_by_name = index_payloads_by_id(args.inventory, diagnostics, "inventory")
    hierarchy_by_id, hierarchy_by_name = index_payloads_by_id(args.hierarchy_index, diagnostics, "hierarchy-index")

    canonical_ids = set(rich_records)
    diagnostics.orphan_super_files = sorted(set(super_by_id) - canonical_ids)
    diagnostics.orphan_generated_files = find_generated_orphans(args.out_dir, canonical_ids)
    diagnostics.stale_app_disorders = diagnostics.orphan_generated_files[:]

    if args.clean_stale_generated or args.dry_run:
        clean_orphans(diagnostics.orphan_generated_files, args.out_dir, args.dry_run, diagnostics)

    configs: list[dict[str, Any]] = []
    for did in sorted(rich_records):
        record = rich_records[did]
        super_payload = lookup_aux(record, super_by_id, super_by_name, "super_enrichment", diagnostics)
        cid11_payload = lookup_aux(record, cid11_by_id, cid11_by_name, "cid11", diagnostics)
        master_payload = lookup_aux(record, master_by_id, master_by_name, "master_index", diagnostics)
        inventory_payload = lookup_aux(record, inventory_by_id, inventory_by_name, "inventory", diagnostics)
        hierarchy_payload = lookup_aux(record, hierarchy_by_id, hierarchy_by_name, "hierarchy", diagnostics)
        merged = merge_disorder(record, super_payload, cid11_payload, master_payload, inventory_payload, hierarchy_payload, diagnostics)
        config = make_config(merged)
        configs.append(config)
        disorder_dir = args.out_dir / did
        try:
            write_text(disorder_dir / "schema.ts", render_schema_ts(did), args.dry_run)
            write_text(disorder_dir / "data.ts", render_data_ts(did, merged), args.dry_run)
            write_text(disorder_dir / "config.ts", render_config_ts(config), args.dry_run)
            write_text(disorder_dir / "index.tsx", render_index_tsx(did, config), args.dry_run)
        except Exception as exc:  # noqa: BLE001 - diagnostic tool must continue across disorders
            diagnostics.component_generation_errors.append({"id": did, "error": str(exc)})

    diagnostics.total_disorders_generated = len(configs)
    if diagnostics.expected_disorders_count is not None and len(configs) != diagnostics.expected_disorders_count:
        diagnostics.warnings.append(
            f"Generated {len(configs)} disorders, expected {diagnostics.expected_disorders_count}. "
            "Check whether rich-dir is complete or pass --expected-count with the canonical value."
        )

    write_text(args.out_dir / "registry.ts", render_registry_ts(configs), args.dry_run)
    write_text(args.out_dir / "index.ts", render_index_aggregator(configs), args.dry_run)
    write_text(args.out_dir / "schemas.ts", render_schemas_aggregator(configs), args.dry_run)
    # Even in --dry-run mode the diagnostic report is intentionally written;
    # dry-run only suppresses generated modules and destructive cleanup.
    write_json(args.diagnostics, diagnostics.to_dict(), False)
    return diagnostics


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate DSM disorder TypeScript/React modules from rich JSON sources.")
    parser.add_argument("--rich-dir", type=Path, default=Path("dsm/output/json"), help="Directory with rich chapter JSON files.")
    parser.add_argument("--super-dir", type=Path, default=Path("dsm/output/json_super_adicionado"), help="Directory with super-enriched disorder JSON files.")
    parser.add_argument("--cid11", type=Path, default=Path("dsm/output/cid11_map.json"), help="CID-11 map JSON keyed by disorder id.")
    parser.add_argument("--master-index", type=Path, default=Path("dsm/output/master_index_mod.json"), help="Master index JSON with clinical/coding metadata.")
    parser.add_argument("--inventory", type=Path, default=Path("dsm/output/inventario_consolidado.json"), help="Consolidated clinical inventory JSON.")
    parser.add_argument("--hierarchy-index", type=Path, default=Path("dsm/output/indice_hierarquias_mod.json"), help="Hierarchy/exclusion/precedence index JSON.")
    parser.add_argument("--out-dir", type=Path, default=Path("src/generated/disorders"), help="Output directory for generated modules.")
    parser.add_argument("--diagnostics", type=Path, default=Path("generation_diagnostics.json"), help="Diagnostics report path.")
    parser.add_argument("--expected-count", type=int, default=58, help="Expected canonical renderable disorder count. Use 0 to disable.")
    parser.add_argument("--dry-run", action="store_true", help="Analyze and report without writing generated files or deleting stale output.")
    parser.add_argument("--clean-stale-generated", action="store_true", help="Remove stale generated disorder directories under --out-dir only.")
    args = parser.parse_args(argv)
    if args.expected_count == 0:
        args.expected_count = None
    return args


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    diagnostics = generate(args)
    print(json.dumps(diagnostics.to_dict(), ensure_ascii=False, indent=2))
    return 1 if diagnostics.schema_generation_errors or diagnostics.component_generation_errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
